export const DELETION_ERROR = "Deletion failed";
export const NO_RECORD_FOUND = "No Record found!";


export const CREATION_SUCCESS = "SUCCESSFULLY CREATED NEW INSTANCE";
export const CREATION_FAILURE = "ERROR CREATING NEW INSTANCE";

export const GET_FAILURE = "SOME ERROR OCCURED WHILE FETCHING!"